site_name: Emre Akgün Dökümantasyon

theme:
  name: material
  palette:

    # Light mode (varsayılan)
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-3
        name: Karanlık moda geç

    # Dark mode
    - scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Aydınlık moda geç

  logo: images/mercedes-benz-1-logo-png-transparent.png
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - content.code.annotate

  font:
    text: Roboto
    code: Fira Code

markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
      linenums: true
  - admonition
  - attr_list


nav:
  - Ana Sayfa: index.md
  - Hakkımda: about.md
  - Projeler:
      - MarineMath: projects/marinemath/index.md
  - Bilgi Bankası:
      - Python: knowledge-base/python/index.md
  - Notlar:
      - Genel Notlar: notes/index.md
      - Kurulum Rehberi: notes/00-setup-guide.md

  - Kaynaklar: references.md
