site_name: Emre Akgün Dökümantasyon

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-3
        name: Karanlık moda geç
    - scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Aydınlık moda geç
  logo: public/images/mercedes-benz-1-logo-png-transparent.png
  favicon: public/images/favicon.ico
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - search.highlight
    - navigation.top
    - content.code.copy
  font:
    text: Roboto
    code: Fira Code

markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
      linenums: true
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Ana Sayfa: index.md
  - Projeler:
      - ProjeÖrnek: public/projects/index.md
  - Bilgi Bankası:
      - Kullanım Rehberi: public/knowledge-base/00-setup-guide.md
      - Python:
          - Sayısal Analiz: 
              - Modelleme ve Hata Hesaplama: public/knowledge-base/python/numerical_analysis/numerical_analysis_modelleme.md
          - Grafik Oluşturma: public\knowledge-base\python\graph\graph.md
  - Notlar:
      - Genel Not: public\notes\general.md
      - Sayısal Analiz: public/notes/sayısal-analiz-kavramları.md
  - Kaynaklar: public/references.md
  - Gizli Projeler:
      - MarineMath: private/projects/marinemath/index.md
  - Gizli Not: private/gizli.md
