site_name: Emre Akgün Dökümantasyon

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-3
        name: Karanlık moda geç
    - scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Aydınlık moda geç
  logo: public/images/mercedes-benz-1-logo-png-transparent.png
  favicon: public/images/favicon.ico
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - search.highlight
    - navigation.top
    - content.code.copy
  font:
    text: Roboto
    code: Fira Code

markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
      linenums: true
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Ana Sayfa: index.md
  - Projeler:
      - Projerim Hakkında: public/projects/index.md
      - MarineMath (CustomTkinter Desktop App):
          - İndex: public/projects/MarineMath-CustomTkinter-Desktop-App/index.md
          - UI ve Kullanım: public/projects/MarineMath-CustomTkinter-Desktop-App/ui-usage.md
          - Uygulamanın Yapısı: public/projects/MarineMath-CustomTkinter-Desktop-App/architecture.md
          - Database: public/projects/MarineMath-CustomTkinter-Desktop-App/database.md
  - Bilgi Bankası:
      - Kullanım Rehberi: public/knowledge-base/00-setup-guide.md
      - Python:
          - Sayısal Analiz: 
              - Optimizasyon/Minimizasyon: public/knowledge-base/python/numerical_analysis/optimizasyon-minimizasyon/optimizasyon-minimizasyon.md
              - İnterpolasyon ve Regresyon: public/knowledge-base/python/numerical_analysis/Interpolasyon-ve-Regresyon/Interpolasyon-ve-Regresyon.md
          - Grafik Oluşturma: 
              - Temel Grafikler: public\knowledge-base\python\graph\graph.md
  - Notlar:
      - İlerleme Notu: public\notes\general.md
      - Sayısal Analiz: public/notes/sayısal-analiz-kavramları.md
      - İstatistik Fizik Laboratuvarı Dağılımlar: public/notes/istatistikfizik.md
  - Kaynaklar: public/references.md
  - Gizli Projeler:
      - MarineMath: private/projects/marinemath/index.md
  - Gizli Not:
    - Gizli Notlarım: private/gizli.md
    - Portfolio Sitesi Kararları: private/portfolio-site.md
